[package]
name = "sapfire"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glam = "0.23.0"
glfw = "0.51.0"
glium = "0.32.1"
