[package]
name = "sapfire_renderer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glam = "0.23.0"
gl = "0.14.0"

[dependencies.glfw]
version = "*"